import { Geist, Geist_Mono } from "next/font/google";
import { Raleway } from "next/font/google";
import "./globals.css";

const font = Raleway({
  weight: ['400', '700'], // Pesos: normal (400) e negrito (700)
  style: ['normal', 'italic'], // Estilos: normal e itálico
  subsets: ['latin'], // Subconjunto de caracteres
  display: 'swap', // Estratégia de renderização
})

export const metadata = {
  title: "Ingryd Siqueira Psi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        {children}
      </body>
    </html>
  );
}
